name: Build image and push to Docker Hub on release

on:
  release:
    types: [published, edited]

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    # ...but only when a `release` is `published`
    if: github.event_name == 'release' # && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          name:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to the Docker Hub
        uses: docker/build-push-action@v3 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        # if: ${{ github.ref == 'ref/head/master' }}
        with:
          platforms: linux/amd64,linux/arm64
          tag_with_ref: true # Info: https://github.com/docker/build-push-action/tree/releases/v1#tag_with_ref
          tag_with_sha: true # Info: https://github.com/docker/build-push-action/tree/releases/v1#tag_with_sha
          tags: latest
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
